force-app/main/default/objects/Whos_Viewing__e/Whos_Viewing__e.object-meta.xml
<CustomObject>
    <label>Who&apos;s Viewing</label>
    <pluralLabel>Who&apos;s Viewing</pluralLabel>
</CustomObject>

force-app/main/default/objects/Whos_Viewing__e/fields/Response_To__c.field-meta.xml
<CustomField>
    <fullName>Response_To__c</fullName>
    <label>Response To</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Whos_Viewing__e/fields/Viewing_State__c.field-meta.xml
<CustomField>
    <fullName>Viewing_State__c</fullName>
    <label>Viewing State</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WhosViewingUtility.cls
/**
 * @description Class to publish an event that a user started viewing a given record.
 * based on : https://github.com/jlondrejcka/Salesforce-Lightning-Component-Whos-Viewing-My-Record
 */
public with sharing class WhosViewingUtility {
    @AuraEnabled
    public static String publishUpdate(String recId, String viewingState, String responseTo) {
        // init val to return to view
        string response = '';

        // create a new event to be published to event bus
        List<Whos_Viewing__e> viewing = new List<Whos_Viewing__e>();
        viewing.add(new Whos_Viewing__e(Record_Id__c = recId, Viewing_State__c = viewingState, Response_To__c = responseTo));

        // call method to publish events
        List<Database.SaveResult> results = EventBus.publish(viewing);

        // inspect publishing results
        for (Database.SaveResult sr : results) {
            if (sr.isSuccess()) {
                System.debug('Successfully published event.');
                response = 'success';
            } else {
                for (Database.Error err : sr.getErrors()) {
                    System.debug('Error returned: ' + err.getStatusCode() + ' - ' + err.getMessage());
                }
                response = 'failed';
            }
        }
        // return outcome to the view
        return response;
    }
}